# Generated by Django 5.2.16 on 2026-07-30 16:03

import accounts.models
import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique code identifier e.g. TOUR_MANAGER', max_length=50, unique=True, verbose_name='Role Code')),
                ('name', models.CharField(help_text='Human-readable role title e.g. Tour & Expedition Manager', max_length=100, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('permissions', models.JSONField(blank=True, default=list, help_text='List of RBAC permission keys assigned to this role', verbose_name='Granted Permissions')),
                ('is_system_protected', models.BooleanField(default=False, help_text='System roles cannot be deleted to maintain operational integrity', verbose_name='System Protected')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Soft-Deleted'), ('RESTORE', 'Record Restored'), ('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_LOCK', 'Account Locked'), ('ACCOUNT_UNLOCK', 'Account Unlocked'), ('ROLE_CHANGE', 'Role or Permissions Updated')], db_index=True, max_length=50, verbose_name='Audit Action')),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Target Model Name')),
                ('target_object_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Target Object ID')),
                ('target_representation', models.CharField(blank=True, max_length=255, verbose_name='Target Human String')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Old State Snapshot')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='New State Snapshot')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Client IP Address')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Session Identifier')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('description', models.TextField(blank=True, verbose_name='Action Summary / Context')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL, verbose_name='Actor / Admin User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='idx_audit_actor_time'), models.Index(fields=['action', '-timestamp'], name='idx_audit_action_time'), models.Index(fields=['target_model', 'target_object_id'], name='idx_audit_target')],
            },
        ),
        migrations.CreateModel(
            name='StaffLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Login Time')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Django Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP Address')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser Client')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('device', models.CharField(blank=True, max_length=100, verbose_name='Device Category')),
                ('user_agent', models.TextField(blank=True, verbose_name='Full User Agent String')),
                ('is_successful', models.BooleanField(db_index=True, default=True, verbose_name='Successful Login')),
                ('logout_reason', models.CharField(blank=True, choices=[('USER_LOGOUT', 'User Initiated Logout'), ('SESSION_TIMEOUT', 'Session Inactivity Timeout'), ('PASSWORD_CHANGE', 'Password Changed'), ('FORCE_TERMINATED', 'Force Terminated by Admin'), ('SECURITY_LOCK', 'Account Security Lockout')], max_length=50, null=True, verbose_name='Logout Reason')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geographic Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL, verbose_name='Staff User')),
            ],
            options={
                'verbose_name': 'Staff Login History',
                'verbose_name_plural': 'Staff Login Histories',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='idx_login_user_time'), models.Index(fields=['ip_address', '-login_time'], name='idx_login_ip_time'), models.Index(fields=['session_key'], name='idx_login_session_key')],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, default=accounts.models.default_employee_id, help_text='Unique enterprise employee identifier (e.g., EMP-10001)', max_length=30, unique=True, validators=[accounts.validators.validate_employee_id], verbose_name='Employee ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OPERATIONS_ADMIN', 'Operations Admin'), ('SUPPORT_ADMIN', 'Support Admin')], db_index=True, default='SUPPORT_ADMIN', max_length=30, verbose_name='Administrative Role')),
                ('department', models.CharField(choices=[('EXECUTIVE', 'Executive Management'), ('OPERATIONS', 'Operations & Logistics'), ('SUPPORT', 'Customer Support & Concierge'), ('IT', 'Information Technology & Security'), ('FINANCE', 'Finance & Billing')], db_index=True, default='OPERATIONS', max_length=30, verbose_name='Department')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[accounts.validators.validate_phone_number], verbose_name='Phone Number')),
                ('profile_image', models.CharField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150', max_length=500, verbose_name='Profile Image URL')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online Status')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('is_account_locked', models.BooleanField(db_index=True, default=False, verbose_name='Is Account Locked')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Locked Until')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Login At')),
                ('last_logout_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Logout At')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Operational Activity')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Password Last Changed At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Soft Deleted Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Created By User')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_staff_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By User')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_staff_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Updated By User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Django User')),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted', 'role'], name='idx_staff_del_role'), models.Index(fields=['is_deleted', 'department'], name='idx_staff_del_dept'), models.Index(fields=['is_deleted', 'is_account_locked'], name='idx_staff_del_locked')],
                'constraints': [models.CheckConstraint(condition=models.Q(('failed_login_attempts__gte', 0)), name='chk_staff_failed_attempts_positive')],
            },
        ),
    ]
