# Generated by Django 6.0.6 on 2026-07-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Soft-Deleted'), ('RESTORE', 'Record Restored'), ('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_LOCK', 'Account Locked'), ('ACCOUNT_UNLOCK', 'Account Unlocked'), ('ROLE_CHANGE', 'Role or Permissions Updated'), ('TOUR_CREATE', 'Tour Created'), ('TOUR_UPDATE', 'Tour Updated'), ('TOUR_DELETE', 'Tour Deleted'), ('TOUR_IMAGE_UPLOAD', 'Tour Image Uploaded'), ('TOUR_IMAGE_DELETE', 'Tour Image Deleted'), ('TOUR_PRICE_CHANGE', 'Tour Price Changed'), ('CONSULTATION_RESOLVED', 'Consultation Resolved'), ('CONSULTATION_UPDATE', 'Consultation Status Updated'), ('STAFF_CREATE', 'Staff Account Created'), ('STAFF_UPDATE', 'Staff Profile Updated'), ('STAFF_DELETE', 'Staff Deactivated')], db_index=True, max_length=50, verbose_name='Audit Action'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('JUNIOR_ADMIN', 'Junior Admin'), ('SENIOR_ADMIN', 'Senior Admin'), ('SUPER_ADMIN', 'Super Admin')], db_index=True, default='JUNIOR_ADMIN', max_length=30, verbose_name='Administrative Role'),
        ),
    ]
