// server/models/visaModel.js
// Authoritative Global Country List and Visa Rule Model for Travel Agencies

export const ALL_WORLD_COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const SPECIALIZED_TRAVEL_RULES = [
  {
    nationalityAliases: ["india", "indian", "in"],
    destinationAliases: ["united states", "usa", "us", "america"],
    purpose: "tourism",
    data: {
      category: "embassy_visa_required",
      summary:
        "Indian passport holders require a US B1/B2 Nonimmigrant Visitor Visa to enter the United States for holiday, package tours, or family visits. Consular interview and OFC biometrics at a US Embassy/Consulate in India are mandatory.",
      maxStayDays: 180,
      processingTime:
        "30 to 180 days (Appointment Slot Dependent at US Embassy New Delhi/Mumbai/Chennai/Hyderabad/Kolkata)",
      estimatedCost: {
        amount: 185,
        currency: "USD",
        formatted: "$185 USD (~₹15,500 INR MRV Fee)",
      },
      officialApplicationUrl: "https://ceac.state.gov/genniv/",
      passportRequirements: {
        minValidityMonths: 6,
        minBlankPages: 2,
        note: "Indian passport must be valid for at least 6 months beyond intended date of departure from the USA with at least 2 blank pages.",
      },
      documentChecklist: [
        {
          id: "doc-in-us-1",
          category: "mandatory",
          title: "Original Indian Passport & Old Passports",
          description:
            "Current Indian passport with minimum 6 months validity from departure date plus all previous passports showing prior travel history.",
          requiredFor: "OFC Biometrics & Consular Interview",
        },
        {
          id: "doc-in-us-2",
          category: "mandatory",
          title:
            "Form DS-160 Online Nonimmigrant Visa Application Confirmation Page",
          description:
            "Printed barcode confirmation page from the official CEAC US Department of State portal.",
          requiredFor: "US Embassy Interview Entry",
        },
        {
          id: "doc-in-us-3",
          category: "mandatory",
          title: "US Visa Appointment Confirmation & MRV Fee Receipt",
          description:
            "Official appointment letter for OFC (Biometrics/Photo) and Consular Interview at US Embassy/Consulate.",
          requiredFor: "Security Access at US Embassy",
        },
        {
          id: "doc-in-us-4",
          category: "mandatory",
          title: "US Specification Photographs (2x2 Inches)",
          description:
            "Two physical color photos (51x51 mm) with plain white background, taken within last 6 months without eyeglasses.",
          requiredFor: "Physical Application Dossier",
        },
        {
          id: "doc-in-us-5",
          category: "mandatory",
          title: "Travel Agency Package Itinerary & Flight Reservations",
          description:
            "Detailed day-wise USA tour package itinerary, hotel vouchers, and roundtrip flight reservations provided by travel agency.",
          requiredFor: "Consular Inspection of Trip Purpose",
        },
        {
          id: "doc-in-us-6",
          category: "mandatory",
          title: "Proof of Financial Solvency (Bank Statements - 6 Months)",
          description:
            "Original bank statements for the last 6 months stamped and signed by the bank manager demonstrating adequate liquid funds (minimum ₹5,000,000+ per traveler recommended).",
          requiredFor: "Proof of Financial Capacity",
        },
        {
          id: "doc-in-us-7",
          category: "mandatory",
          title: "Income Tax Returns (ITR-V) - Last 3 Years",
          description:
            "Income Tax Acknowledgement receipts for last 3 financial years (ITR-V and Form 16/Form 26AS).",
          requiredFor: "Demonstration of Indian Tax & Financial Ties",
        },
        {
          id: "doc-in-us-8",
          category: "mandatory",
          title: "Employment NOC / Business Registration Proof",
          description:
            "NOC / Approved Leave Sanction letter with salary slips for employed individuals; GST Certificate / Partnership Deed for business owners.",
          requiredFor: "Proof of Strong Ties to India",
        },
        {
          id: "doc-in-us-9",
          category: "recommended",
          title: "Comprehensive US Overseas Travel Insurance",
          description:
            "Medical coverage up to $100,000 USD including emergency hospitalization, repatriation, and trip cancellation.",
          requiredFor: "Medical Financial Protection",
        },
        {
          id: "doc-in-us-10",
          category: "conditional",
          title:
            "Sponsorship Letter & Form I-134 (If Sponsored by US Relative)",
          description:
            "Form I-134 Affidavit of Support, US tax documents (W-2), and invitation letter if visiting relatives in the US.",
          requiredFor: "Sponsored Visitors",
        },
      ],
      digitalArrivalForms: [
        {
          name: "US Customs & Border Protection (CBP) I-94 Entry Record",
          submissionWindow:
            "Generated automatically at US Port of Entry (Airport)",
          url: "https://i94.cbp.dhs.gov/I94/#/home",
          mandatory: true,
        },
      ],
      healthAndVaccination: [
        {
          requirement: "Routine Medical Clearance",
          details:
            "No mandatory vaccinations or health quarantine required for travelers from India.",
          mandatory: false,
        },
      ],
      transitRules:
        "US C-1 Transit Visa required if transiting through any US airport without a B1/B2 visa.",
      currencyAndCustoms:
        "Customs declaration required for cash/currency over $10,000 USD (or equivalent). Currency and gold instruments must be declared upon arrival.",
      groundingSources: [
        {
          title: "US Embassy & Consulates in India Official Portal",
          uri: "https://in.usembassy.gov/visas/",
        },
        {
          title: "US Department of State Travel - B1/B2 Visitor Visa",
          uri: "https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html",
        },
        {
          title: "US Travel Docs India Appointment Booking Portal",
          uri: "https://www.ustraveldocs.com/in/",
        },
      ],
      lastVerifiedDate: new Date().toISOString().split("T")[0],
    },
  },
];

export function getCountriesList() {
  return ALL_WORLD_COUNTRIES;
}

export function findSpecializedRule(nationality, destination) {
  const normNat = (nationality || "").trim().toLowerCase();
  const normDest = (destination || "").trim().toLowerCase();

  for (const rule of SPECIALIZED_TRAVEL_RULES) {
    const natMatch = rule.nationalityAliases.some(
      (alias) => normNat.includes(alias) || alias.includes(normNat),
    );
    const destMatch = rule.destinationAliases.some(
      (alias) => normDest.includes(alias) || alias.includes(normDest),
    );
    if (natMatch && destMatch) {
      return rule.data;
    }
  }
  return null;
}
